# Generated by Django 5.0.1 on 2024-01-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='hey image.png', upload_to='product_image/'),
            preserve_default=False,
        ),
    ]
