# Generated by Django 5.0.1 on 2024-02-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_user_user_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
