# Generated by Django 5.0.1 on 2024-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('preparing', 'Tayyorlanmoqda'), ('delivering', 'Yetkazilmoqda'), ('finished', 'Yetkazib berildi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
