# Generated by Django 5.0 on 2024-02-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_history_status_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file_id',
            field=models.CharField(default='AgACAgIAAxkDAAMLZcTPU965Fb5BLAABu9eUq-rLfDBcAAL80TEbvb0oSo82ajg0n7kXAQADAgADeAADNAQ', max_length=1000),
            preserve_default=False,
        ),
    ]
