# Generated by Django 5.0 on 2024-02-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_image_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_file_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
