# Generated by Django 5.0 on 2024-02-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_product_image_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_file_id',
        ),
    ]
